/*
https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/
#include <iostream>

using namespace std;

void fibonacci(){
    int limit = 4000000,
	firstNumber = 1,
	secondNumber= 1;
	long int sum = 0;

	while(secondNumber < limit){
		if((firstNumber + secondNumber)%2 == 0){
			sum += firstNumber + secondNumber;
		}
		int temp = secondNumber;
		secondNumber = firstNumber + secondNumber;
		firstNumber = temp;
	}
	cout << endl << "Sum: "<< sum;
}

int main()
{
    fibonacci();
    return 0;
}
